# -*- coding: utf-8 -*-
"""
/***************************************************************************
 frmTools
                                 A QGIS plugin
 conjunto de herramientas utiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-28
        copyright            : (C) 2021 by jlmw78
        email                : j@j.j
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load frmTools class from file frmTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .frm_tools import frmTools
            
    return frmTools(iface)
